from __future__ import annotations
import re
from typing import Any, Dict, List, Optional
from .base import VendorAdapter
from ..models import (
    NormalizedConfig, InterfaceIP, Route,
    SectionSchema, SectionColumn
)
from ..utils import maybe_prefix_or_mask


class ZTEAdapter(VendorAdapter):
    vendor_id = "zte"
    label = "ZTE (Titan)"
    default_extension = ".txt"

    def parse_to_normalized(self, text: str) -> NormalizedConfig:
        n = NormalizedConfig()
        lines = text.splitlines()

        # Interfaces e IP (mgmt_eth / vlanXXXX)
        cur_if: Optional[str] = None
        for line in lines:
            l = line.strip()
            m = re.match(r"interface\s+(\S+)", l, re.I)
            if m:
                cur_if = m.group(1)
                continue
            if cur_if and l.lower().startswith("ip address"):
                ip, tail = maybe_prefix_or_mask(l)
                if ip:
                    # ZTE geralmente usa máscara, mas também pode aparecer /xx
                    n.interfaces.append(InterfaceIP(ifname=cur_if, vlan=None, ip=ip, prefix_or_mask=tail))
            if l.startswith("$") or l.startswith("!") or l.lower() == "exit":
                cur_if = None

        # Rotas (best-effort)
        for line in lines:
            m = re.match(r"ip\s+route\s+(\S+)\s+(\S+)", line.strip(), re.I)
            if m:
                n.routes.append(Route(prefix=m.group(1), next_hop=m.group(2)))

        # ONU vlan profiles (mantido em extras para você expandir)
        # Ex.: 'onu profile vlan NOME tag-mode tag cvlan 1041'
        profs = []
        for line in lines:
            m = re.search(r"onu\s+profile\s+vlan\s+(.+?)\s+.*\bcvlan\s+(\d+)", line.strip(), re.I)
            if m:
                profs.append({"name": m.group(1).strip(), "cvlan": int(m.group(2))})
        if profs:
            n.extras["onu_vlan_profiles"] = profs

        return n

    def schema(self) -> List[SectionSchema]:
        return [
            SectionSchema(
                key="interfaces",
                title="IPs / Interfaces",
                columns=[
                    SectionColumn("ifname", "Interface", editable=True),
                    SectionColumn("ip", "IP", editable=True),
                    SectionColumn("prefix_or_mask", "Prefixo/Máscara", editable=True),
                ],
            ),
            SectionSchema(
                key="routes",
                title="Rotas",
                columns=[
                    SectionColumn("prefix", "Prefixo", editable=True),
                    SectionColumn("next_hop", "Next-hop", editable=True),
                ],
            ),
            SectionSchema(
                key="onu_vlan_profiles",
                title="ONU Profile VLAN",
                description="Extraído de 'onu profile vlan ... cvlan <id>'.",
                columns=[
                    SectionColumn("name", "Nome", editable=True),
                    SectionColumn("cvlan", "C-VLAN", editable=True, col_type="int"),
                ],
            ),
        ]

    def from_normalized(self, normalized: NormalizedConfig) -> Dict[str, List[Dict[str, Any]]]:
        data: Dict[str, List[Dict[str, Any]]] = {s.key: [] for s in self.schema()}

        data["interfaces"] = [{
            "ifname": i.ifname,
            "ip": i.ip,
            "prefix_or_mask": i.prefix_or_mask,
        } for i in normalized.interfaces]

        data["routes"] = [{"prefix": r.prefix, "next_hop": r.next_hop} for r in normalized.routes]

        data["onu_vlan_profiles"] = normalized.extras.get("onu_vlan_profiles", [])

        return data

    def render(self, target_data: Dict[str, List[Dict[str, Any]]]) -> str:
        out: List[str] = []
        out.append("! Generated by OLT Config Migrator")
        out.append("!")

        for itf in target_data.get("interfaces", []):
            ifname = str(itf.get("ifname", "")).strip()
            ip = str(itf.get("ip", "")).strip()
            mask = str(itf.get("prefix_or_mask", "")).strip()
            if ifname and ip:
                out.append(f"interface {ifname}")
                if mask:
                    if mask.startswith("/"):
                        out.append(f"  ip address {ip}{mask}")
                    else:
                        out.append(f"  ip address {ip} {mask}")
                else:
                    out.append(f"  ip address {ip}")
                out.append("$")

        for r in target_data.get("routes", []):
            prefix = str(r.get("prefix", "")).strip()
            nh = str(r.get("next_hop", "")).strip()
            if prefix and nh:
                out.append(f"ip route {prefix} {nh}")

        for p in target_data.get("onu_vlan_profiles", []):
            name = str(p.get("name", "")).strip()
            cvlan = int(p.get("cvlan", 0) or 0)
            if name and cvlan:
                out.append(f"onu profile vlan {name} tag-mode tag cvlan {cvlan}")

        out.append("!")
        return "\n".join(out)
